import os

DEFAULT_SCENE_THRESHOLD = 30.0
MAX_FRAMES_PER_SCENE = 3
CONTACT_SHEET = False
TILE = 448

# On CUDA fp16, on MPS/CPU - float32
USE_FP16 = False

# Apple FastVLM defaults
DEFAULT_MODEL_ID = os.getenv("FASTVLM_MODEL", "apple/FastVLM-1.5B")
DEFAULT_MAX_TOKENS = int(os.getenv("MAX_NEW_TOKENS", "128"))

PATCH_MULT = 14
